//! Video-detail types.

/// Compact video information returned from search results, trending,
/// playlists, and channels.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VideoSummary {
    /// 11-character YouTube video ID.
    pub id: String,
    /// Video title (plain text).
    pub title: String,
    /// Channel display name.
    pub author: String,
    /// Channel ID (`UC...`).
    pub channel_id: String,
    /// View count, parsed from the human-readable string InnerTube returns
    /// (e.g. `1.2M`). `None` if InnerTube omits it.
    pub view_count: Option<u64>,
    /// Approximate view count text exactly as InnerTube returns it, e.g.
    /// `1.2M views`. Kept distinct from `view_count` for callers that want
    /// the localized string.
    pub view_count_text: Option<String>,
    /// Video length, formatted as `M:SS` or `H:MM:SS`. `None` for live or
    /// upcoming videos.
    pub length_text: Option<String>,
    /// Length in seconds, parsed from `length_text` where possible.
    pub length_seconds: Option<u64>,
    /// Thumbnail URL for the highest-quality thumbnail InnerTube mentions.
    pub thumbnail_url: Option<String>,
}

/// Detailed video metadata. Built from InnerTube's `next` endpoint augmented
/// with bits from `player.playbackTracking`. This type intentionally does not
/// duplicate [`Stream`]-level information — call
/// [`crate::InnerTube::streams`] for that.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VideoDetails {
    /// 11-character YouTube video ID.
    pub id: String,
    /// Video title (plain text).
    pub title: String,
    /// Video description as plain text. Newlines preserved.
    pub description: String,
    /// Channel display name.
    pub author: String,
    /// Channel ID (`UC...`).
    pub channel_id: String,
    /// Subscriber count text exactly as shown on YouTube, e.g. `12.4M
    /// subscribers`. `None` if unavailable.
    pub subscriber_count_text: Option<String>,
    /// View count text exactly as InnerTube returns it.
    pub view_count_text: Option<String>,
    /// Like count, parsed when possible.
    pub likes: Option<u64>,
    /// Upload date string (e.g. `Jan 5, 2025`).
    pub publish_date: Option<String>,
    /// Total video length in seconds.
    pub length_seconds: Option<u64>,
    /// Keywords/tags, when InnerTube exposes them.
    pub keywords: Vec<String>,
    /// `true` if the video is live at the time of the request.
    pub is_live: bool,
    /// `true` if the video is upcoming (premieres later).
    pub is_upcoming: bool,
    /// Best-effort thumbnail URL.
    pub thumbnail_url: Option<String>,
    /// Recommended follow-up videos (limited to the first page returned by
    /// InnerTube — use [`crate::InnerTube::continuation`] to fetch more).
    pub related: Vec<VideoSummary>,
}

/// A single caption track for a video.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Caption {
    /// BCP-47 language code, e.g. `en` or `pt-BR`.
    pub lang: String,
    /// Human-readable name (e.g. `English (auto-generated)`).
    pub name: String,
    /// URL of the WebVTT representation of the track. The URL is a fully
    /// resolved Google CDN URL; the response body may still need a light
    /// transformation from TTML/timedtext to VTT depending on the inner
    /// `fmt` parameter.
    pub vtt_url: String,
    /// Whether the track is auto-generated by YouTube.
    pub is_auto_generated: bool,
}
